### ISSUE TITLE
Bank load from Kijimi fails

### ISSUE THREAD

**Issue by markusschloesser** [RitaAndAurora/kijimi-babu-frik#1]
while general communication works, bank load fails after 5% ("Oups, there was a problem loading the bank from KIJIMI..."). tried multiple banks
Win10 1909, stand-alone babufrik, iConnectivity mio10 midi interface, kijimi connected over midi

**Comment by rkukuchka** [comment]
I'm seeing this as well

macOS 10.15.7, stand-alone, iConnectivity mioXL, kijimi over DIN

**Comment by ffont** [comment]
Hi @markusschloesser, @rkukuchka, thanks for your comment.
This happens when Babu Firk is not receiving sysex from Kijimi. You need to make sure that you have configured MIDI input in Babu Frik properly. You should also see how changing presets in KIJIMI does not update the state in Babu Frik. Try the following:

1. If you're using MIDI through DIN5, you should have a MIDI cable form the KIJIMI MIDI out to your interface MIDI in as well, and configure Babu Frik to receive MIDI at the right interface and channel. 
2. If you're using MIDI through DIN5, you should make sure that your interface is not filtering out MIDI sysex messages.
3. If you're sure about points 1 and 2 but still can't load a bank from KIJIMI, try connecting to KIJIMI through USB MIDI and see if it works (you'll need to reconfigure Babu Frik to use the USB interface). Connecting to KIJIMI both ways through MIDI DIN5 has not been well tested and currently the recommendation would be to use the USB connection.

**Comment by rkukuchka** [comment]
Hi @ffont, 
- Bidirectional MIDI is setup on the DIN5s
- I have other editors working on the interface, so doubtful about filterin

I can try with using USB MIDI but I picked up the iConnectivity to offload devices off of my MIDI bus intentionally as I have a larger hardware setup. The mioXL is a mixture of USB and DIN midi

**Comment by jboswell23** [comment]
I'm also seeing the same issue as rkukuchka- I've verified taht I have bidirectional MIDI (DIN5) working on my interface (EDIROL UM-880).  I've verified there is no sysex filtering and toggled both the generic midi protocol setting as well as the standard Mac OS X host driver.   I can make changes to the patch over MIDI, just can't load/save banks to/from KIJIMI over MIDI (DIN5).

When using KIJIMI over USB, I can load banks, but this is not the preferred mode in my setup.

**Comment by markusschloesser** [comment]
bidirectional is set up, sysex is not filtered (I use sysex going thru the same midi interface for accessing my mks80).
Interestingly I tried to do a sysex backup before upgrading from 1.20 to 1.35 with the procedure mentioned in the manual and had Midi-OX opened and waiting for sysex. Which didn't work (midi-ox didn't receive anything). Now I had done this in the past (thru Midi DIN), but it didn't work with 1.20 and now with babufrik and 1.35. So maybe a BC problem?

**Comment by ffont** [comment]
@jboswell23 @markusschloesser if you can confirm that connecting directly with the USB works, this is relevant info. I just made a quick test with a MIDI monitor and it looks like KIJIMI is not sending sysex over the DIN5 port, therefore this is most probably a BC issue. I'll let them know!

**Comment by ffont** [comment]
Closing this issue as should have been fixed in 1.0.1 release

**Comment by markusschloesser** [comment]
can confirm that it works now, thanks!
