### ISSUE TITLE
UI Issue: last row missing

### ISSUE THREAD

**Issue by markusschloesser** [RitaAndAurora/kijimi-babu-frik#2]
the last row (with "Load patch from file", "Settings" etc) vanishes when I enable the LFO panel and does not return when disabling the LFO panel. closing and reopening fixes the problem, happening on all screens.
3 screens: 4k (150% scaling) + 1920x1200 + 1024x768, 
Win10x64 1909

**Comment by rkukuchka** [comment]
If you scroll down you'll see it, but I've found the scroll view feels a bit sluggish

**Comment by markusschloesser** [comment]
Doesn't work, tried all the scrolling in the world 😊

**Comment by ffont** [comment]
Hi @markusschloesser, @rkukuchka,
As @rkukuchka says, you should be able to see the last row by scrolling if it does not fit on screen. When panels are added/removed, Babu Frik should resize automatically. You mention scrolling does not work, but do you see the scroll bars? It could be that these are hidden, check the `View...` menu for the option and make sure your scrollbars should be visible. Also try with the scaling of the UI so find an option that allows you to fit all Babu Firk on screen.

If none of this works, please send some screenshots or little video to see the issue in action.

**Comment by markusschloesser** [comment]
BF does resize, but last row does not show. I do see scroll bars. UI scaling doesn't change/fix it
Video here: https://photos.app.goo.gl/b39kxdWgXHEZtCCZA (still processing, so might be limited resolution)

**Comment by ffont** [comment]
Thanks for the video, I think I now know what the issue is. See the "audio input is muted" warning at the top of the window? I this this warning is taking extra space from the UI and renders the lower-row button hidden. If you click settings button in the warning and untick the "Mute audio input" checkbox, the warning will disappear (this is something I should fix in future version) and hopefully you should be seeing the lower row normally. Can you confirm if this fixes the issue? If that is the case I'll add it to the manual.

**Comment by markusschloesser** [comment]
confirmed, unticking "mute audio input" fixes the problem and I didn't need to cycle
